import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Window from '../components/window'
import Contact from '../components/contact'
import Portrait from '../components/portrait'

export default function Home() {
  return (
    <div classNameName={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main classNameName={styles.main}>
        <div className={styles.person}>
      <div className={styles.container}>
        <div className={styles.containerInner}>
        <p>Digital Designer + Developer</p>
      <p className={styles.sofia}>Sample Text</p>
          <img
            className={styles.circle}
            src='/SVG/portrait-bg.svg'
          /> 
          <img
            className={styles.img1}
            src='/SVG/portrait.svg'
          />
        </div>
      </div>
    </div>
        {/* <Window/> */}
        {/* <Contact/> */}

      
      </main>
    </div>
  )
}
